name: my_cv_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  file_picker: ^1.13.0+1
  flutter_rating_bar: ^3.0.1+1
  get_it: ^4.0.4
  google_maps_webservice: ^0.0.17
  google_place: ^0.3.2
  http: ^0.12.2
  image_picker: ^0.6.7+2 
  intl_phone_field: ^1.4.4
  page_transition: ^1.1.5
  percent_indicator: ^2.1.5
  provider: ^4.3.1
  url_launcher: ^5.5.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.1.9

flutter_native_splash:
  image: assets/images/splash_screen.png
  color: "83518C"
  fill: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/login/bg-circles.png
    - assets/images/login/icon-facebook.png
    - assets/images/login/icon-google.png
    - assets/images/login/icon-apple.png
    - assets/images/login/ob_one.png

    - assets/images/firebase_logo.png
    - assets/images/node_logo.png
    - assets/images/flutter_logo.png
    - assets/images/profile_pic.jpg
    - assets/images/validate-icon.png
    
    - lang/en.json
    - lang/es.json

    - config/

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/MuliRegular.ttf
        - asset: assets/fonts/MuliBold.ttf
          weight: 700
        - asset: assets/fonts/MuliLight.ttf
          weight: 300
