name: my_cv_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  get_it: ^7.6.7
  google_place: ^0.4.7
  intl_phone_field: ^3.2.0
  page_transition: ^2.1.0
  percent_indicator: ^4.2.3
  provider: ^6.1.2
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_native_splash: ^2.4.0

# flutter_native_splash:
#   image: assets/images/splash_screen.png
#   color: '83518C'
#   fill: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/login/bg-circles.png
    - assets/images/login/icon-facebook.png
    - assets/images/login/icon-google.png
    - assets/images/login/icon-apple.png
    - assets/images/login/ob_one.png

    - assets/images/firebase_logo.png
    - assets/images/node_logo.png
    - assets/images/flutter_logo.png
    - assets/images/profile_pic.jpg
    - assets/images/validate-icon.png

    - lang/en.json
    - lang/es.json

    - config/

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/MuliRegular.ttf
        - asset: assets/fonts/MuliBold.ttf
          weight: 700
        - asset: assets/fonts/MuliLight.ttf
          weight: 300
